import AdminLayout from "@/components/AdminLayout";
import { trpc } from "@/lib/trpc";
import { Copy, Link2, Megaphone, Percent, Plus, Users } from "lucide-react";
import { useMemo, useState } from "react";
const sources = ["instagram", "tiktok", "whatsapp", "telegram", "google"] as const;
export default function MarketingDashboard() {
  const settings = trpc.settings.get.useQuery(); const marketers = trpc.marketers.list.useQuery(); const partners = trpc.partners.list.useQuery(); const orders = trpc.orders.list.useQuery(); const utils = trpc.useUtils();
  const create = trpc.marketers.create.useMutation({ onSuccess: () => { setName(""); setCode(""); setPercent("10"); void utils.marketers.list.invalidate(); } });
  const [source, setSource] = useState<(typeof sources)[number]>("instagram"); const [campaign, setCampaign] = useState(""); const [content, setContent] = useState(""); const [copied, setCopied] = useState(false); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [percent, setPercent] = useState("10");
  const url = useMemo(() => { const params = new URLSearchParams({ partner: code || "partner_code", utm_source: source, utm_medium: source === "google" ? "cpc" : "social", utm_campaign: campaign || "new_campaign", utm_content: content || "default" }); return `${window.location.origin}/?${params.toString()}`; }, [source, campaign, content, code]);
  const copy = async () => { await navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  const createMarketer = (event: React.FormEvent) => { event.preventDefault(); create.mutate({ name, code, commissionPercent: Number(percent) }); };
  return <AdminLayout title="المسوقون والعمولات" description="أنشئي مسوقين بأكواد إحالة، وحددي عمولة كل مسوق، وتابعي المستحقات من الطلبات المدفوعة.">
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">مسوق جديد</span><h2>إضافة مسوق ونسبة عمولته</h2></div><Users size={23} /></div><form className="settings-grid" onSubmit={createMarketer}><label>اسم المسوق<input required value={name} onChange={e => setName(e.target.value)} placeholder="مثال: أحمد" /></label><label>كود الإحالة<input required dir="ltr" pattern="[A-Za-z0-9_-]{2,48}" value={code} onChange={e => setCode(e.target.value.toLowerCase())} placeholder="ahmed10" /></label><label>العمولة %<input required type="number" min="0" max="100" step="0.1" value={percent} onChange={e => setPercent(e.target.value)} /></label><button className="admin-save-button" type="submit" disabled={create.isPending}><Plus size={15} /> {create.isPending ? "جاري الحفظ…" : "إضافة المسوق"}</button></form>{create.error && <p className="form-error">{create.error.message}</p>}</section>
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">المسوقون</span><h2>المستحقات الحالية</h2></div><Percent size={21} /></div>{marketers.data?.length ? <div className="marketers-table">{marketers.data.map(marketer => { const referred = (orders.data ?? []).filter(order => order.referralCode === marketer.code); const paid = referred.filter(order => order.paymentStatus === "paid"); const revenue = paid.reduce((sum, order) => sum + Number(order.orderAmount ?? 0), 0); return <div className="marketer-row" key={marketer.id}><div><b>{marketer.name}</b><small dir="ltr">{marketer.code}</small></div><span>{marketer.commissionPercent}%</span><span>{referred.length} طلب</span><strong>{(revenue * marketer.commissionPercent / 100).toFixed(2)} د.إ مستحق</strong></div>; })}</div> : <p className="settings-help">لا يوجد مسوقون جدد بعد.</p>}</section>
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">النظام السابق محفوظ</span><h2>المسوقون القدامى وروابطهم</h2></div><Link2 size={21} /></div>{partners.data?.length ? <div className="marketers-table">{partners.data.map(partner => { const referred = (orders.data ?? []).filter(order => order.referralCode === partner.code); const paid = referred.filter(order => order.paymentStatus === "paid"); const revenue = paid.reduce((sum, order) => sum + Number(order.orderAmount ?? 0), 0); const commission = partner.commissionType === "percent" ? revenue * Number(partner.commissionValue) / 100 : paid.length * Number(partner.commissionValue); const shortLink = `${window.location.origin}/partner/${partner.code}`; return <div className="marketer-row" key={partner.id}><div><b>{partner.name}</b><small dir="ltr">{partner.code}</small><small>{partner.active ? "فعال" : "موقوف"}</small></div><span>{partner.commissionType === "percent" ? `${partner.commissionValue}%` : `${partner.commissionValue} د.إ`}</span><span>{referred.length} طلب</span><strong>{commission.toFixed(2)} د.إ مستحق</strong><button type="button" className="admin-ghost-button" onClick={() => void navigator.clipboard?.writeText(shortLink)}><Copy size={14} /> نسخ الرابط القديم</button></div>; })}</div> : <p className="settings-help">لا توجد بيانات قديمة ظاهرة حالياً.</p>}</section>
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">رابط المسوق</span><h2>جهّزي رابط الإحالة والحملة</h2></div><Megaphone size={23} /></div><div className="settings-grid"><label>المنصة<select value={source} onChange={e => setSource(e.target.value as typeof source)}>{sources.map(item => <option key={item}>{item}</option>)}</select></label><label>كود المسوق<input dir="ltr" value={code} onChange={e => setCode(e.target.value.toLowerCase())} placeholder="ahmed10" /></label><label>اسم الحملة<input value={campaign} onChange={e => setCampaign(e.target.value)} placeholder="launch_september" /></label><label>اسم الإعلان<input value={content} onChange={e => setContent(e.target.value)} placeholder="reel_01" /></label></div><div className="campaign-url"><Link2 size={17} /><code>{url}</code><button type="button" className="admin-save-button" onClick={copy}><Copy size={15} /> {copied ? "تم النسخ" : "نسخ الرابط"}</button></div><p className="settings-help">أي طلب يصل عبر هذا الرابط ويسجل كمدفوع يحسب عمولته تلقائياً حسب نسبة المسوق.</p></section>
  </AdminLayout>;
}
