import AdminLayout from "@/components/AdminLayout";
import { trpc } from "@/lib/trpc";
import { Copy, Link2, Plus, Save, Users } from "lucide-react";
import { useState } from "react";

const campaignQuery = "utm_source=telegram&utm_medium=group&utm_campaign=telegram_admin";
export default function MarketingDashboard() {
  const partners = trpc.partners.list.useQuery(undefined, { refetchInterval: 10000 });
  const orders = trpc.orders.list.useQuery(undefined, { refetchInterval: 10000 });
  const utils = trpc.useUtils();
  const [name, setName] = useState(""); const [commissionType, setCommissionType] = useState<"fixed" | "percent">("percent"); const [commissionValue, setCommissionValue] = useState("10");
  const create = trpc.partners.create.useMutation({ onSuccess: () => { setName(""); setCommissionValue("10"); void utils.partners.list.invalidate(); } });
  const update = trpc.partners.update.useMutation({ onSuccess: () => void utils.partners.list.invalidate() });
  const copy = async (value: string) => { await navigator.clipboard?.writeText(value); };
  const createPartner = (event: React.FormEvent) => { event.preventDefault(); create.mutate({ name, commissionType, commissionValue }); };
  return <AdminLayout title="المسوقون والعمولات" description="نظام موحد يحافظ على الأكواد والروابط القديمة، ويحسب عمولة كل مسوق من الطلبات المدفوعة.">
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">مسوق جديد</span><h2>إنشاء مسوق ورابط تلقائي</h2></div><Users size={23} /></div><form className="settings-grid" onSubmit={createPartner}><label>اسم المسوق<input required value={name} onChange={e => setName(e.target.value)} placeholder="مثال: أم حليمة" /></label><label>نوع العمولة<select value={commissionType} onChange={e => setCommissionType(e.target.value as "fixed" | "percent")}><option value="percent">نسبة مئوية</option><option value="fixed">مبلغ ثابت لكل طلب</option></select></label><label>قيمة العمولة<input required inputMode="decimal" type="number" min="0" step="0.01" value={commissionValue} onChange={e => setCommissionValue(e.target.value)} /></label><button className="admin-save-button" disabled={create.isPending}><Plus size={15} /> {create.isPending ? "جاري الإنشاء…" : "إضافة وإنشاء الرابط"}</button></form>{create.error && <p className="form-error">{create.error.message}</p>}</section>
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">كل المسوقين</span><h2>القديم والجديد في قائمة واحدة</h2></div><Link2 size={21} /></div>{partners.data?.length ? <div className="marketers-table">{partners.data.map(partner => { const referred = (orders.data ?? []).filter(order => order.referralCode === partner.code); const paid = referred.filter(order => order.paymentStatus === "paid"); const revenue = paid.reduce((sum, order) => sum + Number(order.orderAmount ?? 0), 0); const commission = partner.commissionType === "percent" ? revenue * Number(partner.commissionValue) / 100 : paid.length * Number(partner.commissionValue); const shortLink = `${window.location.origin}/partner/${partner.code}`; const longLink = `${shortLink}?${campaignQuery}`; return <article className="partner-unified-card" key={partner.id}><div className="marketer-row"><div><b>{partner.name}</b><small dir="ltr">{partner.code}</small><small>{partner.active ? "فعال" : "موقوف"}</small></div><span>{partner.commissionType === "percent" ? `${partner.commissionValue}%` : `${partner.commissionValue} د.إ`}</span><span>{referred.length} طلب / {paid.length} مدفوع</span><strong>{commission.toFixed(2)} د.إ مستحق</strong></div><div className="partner-links"><label>الرابط القديم<input dir="ltr" readOnly value={shortLink} /></label><button className="admin-ghost-button" onClick={() => void copy(shortLink)}><Copy size={14} /> نسخ</button><label>الرابط مع حملة<input dir="ltr" readOnly value={longLink} /></label><button className="admin-ghost-button" onClick={() => void copy(longLink)}><Copy size={14} /> نسخ</button><button className="admin-save-button" onClick={() => update.mutate({ id: partner.id, active: !partner.active })} disabled={update.isPending}><Save size={14} /> {partner.active ? "إيقاف" : "تفعيل"}</button></div></article>; })}</div> : <p className="settings-help">لا يوجد مسوقون بعد.</p>}</section>
    <section className="marketing-card"><div className="section-card-heading"><div><span className="section-label">طريقة الحساب</span><h2>العمولة لا تُحسب إلا بعد الدفع</h2></div></div><p className="settings-help">يحفظ النظام كود المسوق لمدة 30 يوماً. عند تسجيل الطلب كمدفوع، تُحسب العمولة حسب النوع المحدد: نسبة من الإيراد أو مبلغ ثابت لكل طلب مدفوع.</p></section>
  </AdminLayout>;
}
