import { trpc } from "@/lib/trpc";
import { contactMethodLabels, formatChildAgeRange, orderStatusLabels } from "@shared/orderFlow";
import { ExternalLink, MessageCircle, RefreshCw } from "lucide-react";
import { useState } from "react";

export default function OrdersDashboard() {
  const orders = trpc.orders.list.useQuery();
  const utils = trpc.useUtils();
  const update = trpc.orders.update.useMutation({ onSuccess: () => void utils.orders.list.invalidate() });
  const [notes, setNotes] = useState<Record<string, string>>({});
  return <main dir="rtl" className="orders-dashboard"><header className="orders-header"><div><span>إدارة بطل قصتي</span><h1>طلبات بدء المحادثة</h1><p>الطلبات الجديدة تظهر هنا. ردي على العميل، ثم حدّثي الحالة حسب الخطوة التي وصل لها.</p></div><button className="nav-button" onClick={() => void orders.refetch()}><RefreshCw size={16} /> تحديث</button></header>
    {orders.isLoading ? <div className="admin-loading">جاري جلب الطلبات…</div> : orders.error ? <div className="admin-error">تعذر جلب الطلبات.</div> : orders.data?.length === 0 ? <div className="admin-empty"><MessageCircle size={32}/><h2>ما وصل طلب بعد</h2><p>بيظهر هنا كل عميل يبدأ النموذج من الموقع.</p></div> : <div className="orders-list">{orders.data?.map(order => <article className="order-item" key={order.reference}><div className="order-main"><div className="order-reference"><span>{order.reference}</span><span>{orderStatusLabels[order.status]}</span></div><h2>{order.childName} <small>· {formatChildAgeRange(order.childAge)}</small></h2><p><b>الاهتمام:</b> {order.childInterest}</p><p><b>التواصل:</b> {contactMethodLabels[order.contactMethod]} — {order.contactValue}</p><div className="order-meta"><span>وصل {new Date(order.createdAt).toLocaleString("ar-AE")}</span><span>{order.telegramOpenedAt ? "فتح تيليجرام" : "لم يؤكد فتح تيليجرام"}</span><span>{order.ownerNotifiedAt ? "تم إرسال تنبيه Discord" : "تحققي من التنبيه"}</span></div></div><div className="order-actions"><label>حالة الطلب<select value={order.status} onChange={event => update.mutate({ reference: order.reference, status: event.target.value as keyof typeof orderStatusLabels, adminNotes: notes[order.reference] ?? order.adminNotes ?? "" })}>{Object.entries(orderStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>ملاحظاتك<textarea rows={3} value={notes[order.reference] ?? order.adminNotes ?? ""} onChange={event => setNotes({ ...notes, [order.reference]: event.target.value })} /></label><button className="nav-button" onClick={() => update.mutate({ reference: order.reference, status: order.status, adminNotes: notes[order.reference] ?? order.adminNotes ?? "" })}>حفظ</button>{order.contactMethod === "telegram" && <a href={`https://t.me/${order.contactValue.replace(/^@/, "")}`} target="_blank" rel="noreferrer">فتح تيليجرام <ExternalLink size={14}/></a>}</div></article>)}</div>}</main>;
}
